[env:esp32dev]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags = -std=gnu++17
build_unflags = -std=gnu++11
lib_deps =
    adafruit/Adafruit PWM Servo Driver Library@^3.0.2
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^6.21.5

[env:native]
platform = native
build_flags = -std=gnu++17 -Iinclude
build_src_filter = +<*> -<main.cpp> -<MockRobotDriver.cpp> -<TrinovaRobot.cpp> -<DcMotorDriver.cpp> -<Pca9685Driver.cpp> -<ServoDriver.cpp> -<HardwareRobotDriver.cpp>
test_framework = unity